name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest          # VS 2022 image with desktop workload
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: msbuild JaperWindowsApplication.sln /p:Configuration=Release
    - name: Package
      run: ./build.ps1
    - name: Test
      run: dotnet test JaperWindowsApplication.sln --no-build --verbosity normal
