name: Package Zip

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: mkdir -p .ZIP
      - run: npm run dist
      - run: mv dist/*.zip .ZIP/

