name: git-sync-with-mirror

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: git-sync
        env:
          git_sync_destination_repo: ${{ secrets.GIT_SYNC_DESTINATION_REPO }}
          git_sync_ssh_private_key: ${{ secrets.GIT_SYNC_SSH_PRIVATE_KEY }}
        if: env.git_sync_destination_repo && env.git_sync_ssh_private_key
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:aws/aws-sdk-js.git"
          source_branch: "master"
          destination_repo: ${{ secrets.GIT_SYNC_DESTINATION_REPO }}
          destination_branch: "master"
          ssh_private_key: ${{ secrets.GIT_SYNC_SSH_PRIVATE_KEY }}
