name: Clone Repositories into Redos

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clone:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout this workflow repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Create redos directory
        run: mkdir -p redos

      - name: Read repos.txt and shallow‑clone each with token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while IFS= read -r repo || [ -n "$repo" ]; do
            [[ -z "$repo" || "$repo" =~ ^\s*# ]] && continue

            # Build the raw HTTPS URL (with .git)
            if [[ "$repo" =~ ^https?:// ]]; then
              raw="$repo"
            else
              raw="https://github.com/${repo}.git"
            fi

            # Inject the token into the URL for auth
            auth="${raw/https:\/\//https:\/\/x-access-token:${GITHUB_TOKEN}@}"

            # Derive folder name & clone
            name=$(basename "$raw" .git)
            echo "Cloning $raw → redos/$name"
            git clone --depth 1 "$auth" "redos/$name"
          done < repos.txt
