name: Clone Repositories into Redos

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  REDOS_DIR: redos

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Ensure redos directory
        run: mkdir -p "${{ env.REDOS_DIR }}"

      - name: Read and clone repos
        run: |
          readarray -t repos < repos.txt
          for repo in "${repos[@]}"; do
            # Skip empty lines or comments
            [[ "$repo" =~ ^\s*# ]] || [[ -z "$repo" ]] && continue

            # Determine clone URL
            if [[ "$repo" =~ ^https?:// ]]; then
              url="$repo"
            else
              url="https://github.com/${repo}.git"
            fi

            # Derive directory name
            dir="${repo##*/}"
            echo "Cloning ${url} into ${REDOS_DIR}/${dir}"
            git clone --depth 1 "$url" "${REDOS_DIR}/${dir}"
          done

      - name: Report status
        run: echo "Cloned ${#repos[@]} repositories into ${REDOS_DIR}."
