name: CLONE

on:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Ensure .github/CLONE.txt has Unix line endings
        run: |
          if command -v dos2unix &> /dev/null; then dos2unix .github/CLONE.txt
          else sed -i 's/\r$//' .github/CLONE.txt; fi

      - name: Create repository directory
        run: mkdir -p repository

      - name: Read and shallow‑clone each repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          shopt -s extglob

          echo "Using .github/CLONE.txt from $(pwd)"
          sed -n '1,20p' .github/CLONE.txt

          while IFS= read -r repo || [[ -n $repo ]]; do
            repo="${repo//$'\r'/}"
            repo="${repo##*( )}"
            repo="${repo%%*( )}"

            echo "➤ raw repo: '$repo'"
            [[ -z "$repo" || "$repo" =~ ^# ]] && { echo "  → skipping"; continue; }

            if [[ "$repo" =~ ^https?:// ]]; then url="$repo"
            else url="https://github.com/$repo.git"; fi

            auth_url="${url/https:\/\//https:\/\/x-access-token:${GITHUB_TOKEN}@}"
            dir="$(basename "$url" .git)"
            echo "Shallow-cloning $url → repository/$dir"
            git clone --depth 1 "$auth_url" "repository/$dir" || {
              echo "❌ Failed to clone $repo"; continue; }
          done < .github/CLONE.txt

      - name: Remove Git metadata from clones
        run: rm -rf repository/*/.git

      - name: Commit cloned repos
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repository
          if git diff --cached --quiet; then
            echo "✨ No changes to commit"
          else
            git commit -m "Add latest snapshots of repos/"
            git push
          fi
