name: Clone Repositories into Redos

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Create redos directory
        run: mkdir -p redos

      - name: Read and shallow‑clone each repo
        env:
          GITHUB_TOKEN: ${{ secrets.OMNI_READONLY }}
        run: |
          while IFS= read -r repo || [ -n "$repo" ]; do
            # Trim whitespace and skip empty/comment lines
            repo="${repo##*( )}"
            repo="${repo%%*( )}"
            [[ -z "$repo" || "$repo" =~ ^# ]] && continue

            # Build HTTPS URL and ensure .git suffix
            if [[ "$repo" =~ ^https?:// ]]; then
              url="$repo"
            else
              url="https://github.com/$repo.git"
            fi

            # Inject token for authentication
            auth_url="${url/https:\/\//https:\/\/x-access-token:${GITHUB_TOKEN}@}"

            # Derive directory name and clone
            dir="$(basename "$url" .git)"
            echo "Cloning $url → redos/$dir"
            git clone --depth 1 "$auth_url" "redos/$dir" || {
              echo "❌ Failed to clone $repo"
              continue
            }
          done < repos.txt
