name: Clone Repositories into Redos

on:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Create redos directory
        run: mkdir -p redos

      - name: Read and shallow‑clone each repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while IFS= read -r repo || [ -n "$repo" ]; do
            repo="${repo##*( )}"
            repo="${repo%%*( )}"
            [[ -z "$repo" || "$repo" =~ ^# ]] && continue

            if [[ "$repo" =~ ^https?:// ]]; then
              url="$repo"
            else
              url="https://github.com/$repo.git"
            fi

            auth_url="${url/https:\/\//https:\/\/x-access-token:${GITHUB_TOKEN}@}"
            dir="$(basename "$url" .git)"
            echo "Cloning $url → redos/$dir"
            git clone --depth 1 "$auth_url" "redos/$dir" || {
              echo "❌ Failed to clone $repo"
              continue
            }
          done < repos.txt

      - name: Commit cloned repos
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add redos
          if git diff --cached --quiet; then
            echo "✨ No changes to commit"
          else
            git commit -m "Add shallow clones in redos/"
            git push
          fi
