name: Init Repository sync

on:
  workflow_dispatch:
    inputs:
      method:
        description: 'clone method: shadow, submodule or subtree'
        required: false
        default: 'shadow'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Validate required secret
        run: |
          if [ -z "${{ secrets.OMNI_READONLY }}" ]; then
            echo "Error: OMNI_READONLY secret is not set"
            exit 1
          fi
      - name: Install dependencies
        run: pip install -r tooling/requirements.txt
      - name: Initialize repositories
        env:
          GITHUB_TOKEN: ${{ secrets.OMNI_READONLY }}
        run: |
          python tooling/sync_repos.py init --org ${{ github.repository_owner }} --method ${{ inputs.method }}
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: initial repository sync"
            git push
          else
            echo "No changes to commit"
          fi
