name: Init Repository sync

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Create workspace folder
        run: mkdir -p repos

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Clone repos from repos.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        run: |
          while IFS= read -r repo || [ -n "$repo" ]; do
            # skip empty lines or comments
            if [[ -z "$repo" || "$repo" =~ ^# ]]; then
              continue
            fi
            echo "Cloning $OWNER/$repo into repos/$repo"
            gh repo clone "${OWNER}/${repo}" "repos/${repo}"
          done < repos.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Initialize repositories
        run: python tooling/sync_repos.py init

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: initial repository sync"
            git push
          fi
