name: Refresh repos.json

on:
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Refresh repos.json
        env:
          GITHUB_TOKEN: ${{ secrets.OMNI_READONLY }}
        run: python tooling/sync_repos.py refresh --org ${{ github.repository_owner }}
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add repos.json
            git commit -m "chore: manual repos.json refresh"
            git push
          fi
